### ISSUE TITLE
OMOO.py script produces singularity error

### ISSUE THREAD

**Issue by rounak-meyur** [openEDI/oedisi-example#47]
The OMOO.py script produces error when integrated with the IEEE123 feeder.
Can you please look into this?

Traceback (most recent call last):
  File "/Users/meyu507/Library/CloudStorage/OneDrive-PNNL/Documents/projects/oedisi_dopf/build_omoo/optimal_pf/OMOO.py", line 728, in <module>
    sfed.run()
  File "/Users/meyu507/Library/CloudStorage/OneDrive-PNNL/Documents/projects/oedisi_dopf/build_omoo/optimal_pf/OMOO.py", line 642, in run
    self.G, self.H, self.w_mag = getLinearModel(self.YLL, self.YL0, self.V0)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/meyu507/Library/CloudStorage/OneDrive-PNNL/Documents/projects/oedisi_dopf/build_omoo/optimal_pf/OMOO.py", line 316, in getLinearModel
    prody = YLLi @ inv(diags(np.conjugate(Vk).squeeze(), format="csc"))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/meyu507/opt/anaconda3/envs/dopf/lib/python3.11/site-packages/scipy/sparse/linalg/_matfuncs.py", line 75, in inv
    Ainv = spsolve(A, I)
           ^^^^^^^^^^^^^
  File "/Users/meyu507/opt/anaconda3/envs/dopf/lib/python3.11/site-packages/scipy/sparse/linalg/_dsolve/linsolve.py", line 299, in spsolve
    Afactsolve = factorized(A)
                 ^^^^^^^^^^^^^
  File "/Users/meyu507/opt/anaconda3/envs/dopf/lib/python3.11/site-packages/scipy/sparse/linalg/_dsolve/linsolve.py", line 597, in factorized
    return splu(A).solve
           ^^^^^^^
  File "/Users/meyu507/opt/anaconda3/envs/dopf/lib/python3.11/site-packages/scipy/sparse/linalg/_dsolve/linsolve.py", line 433, in splu
    return _superlu.gstrf(N, A.nnz, A.data, indices, indptr,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Factor is exactly singular

I have also attached the log file.
[optimal_pf.log](https://github.com/openEDI/oedisi-example/files/13384469/optimal_pf.log)

**Comment by rounak-meyur** [comment]
The feeder federate generates nan values for real and imaginary voltages after the first iteration. This is because of the control commands sent from the omoo federate to the feeder federate. 

The current control commands are as follows
```python
Command(obj_name = pv.loc[i, "name"], obj_property = "%Pmpp", val = str(100 * pmpp[i]))
Command(obj_name = pv.loc[i, "name"], obj_property = "PF", val = str(np.sign(Q_set[i]) * power_factor[i]))
```

If the commands are changed such that power factor is set to be 1.0 for all PV systems, the code works fine.
```python
Command(obj_name = pv.loc[i, "name"], obj_property = "%Pmpp", val = str(100 * pmpp[i]))
Command(obj_name = pv.loc[i, "name"], obj_property = "PF", val = "1.0")
```

For other values of power factor, the code generates an error. The Q set point is probably going out of limits.
